'use client';
import { useState } from 'react';

const Flashcard = ({ question, answer }: { question: string; answer: string }) => {
  const [isFlipped, setIsFlipped] = useState(false);

  return (
    <div 
      className="w-full h-64 cursor-pointer perspective-1000"
      onClick={() => setIsFlipped(!isFlipped)}
    >
      <div className={`relative w-full h-full transition-transform duration-500 preserve-3d ${isFlipped ? 'my-rotate-y-180' : ''}`}>
        
        <div className="absolute w-full h-full backface-hidden bg-white border-2 border-blue-500 rounded-2xl flex flex-col items-center justify-center p-6 shadow-md hover:shadow-xl transition-shadow">
          <span className="text-blue-500 font-bold uppercase tracking-widest text-xs mb-4">Question</span>
          <h2 className="text-xl font-bold text-gray-800 text-center leading-tight">
            {question}
          </h2>
          <p className="mt-4 text-sm text-gray-400">Click to reveal answer</p>
        </div>
                 <div className="absolute w-full h-full backface-hidden bg-blue-600 text-white rounded-2xl flex flex-col items-center justify-start p-6 my-rotate-y-180 shadow-inner">
            <span className="text-blue-200 font-bold uppercase tracking-widest text-[10px] mb-2 sticky top-0 bg-blue-600 w-full text-center pb-2">
              Answer
            </span>
            <div className="overflow-y-auto w-full pr-1 custom-scrollbar">
              <p className="text-sm md:text-base leading-relaxed text-center whitespace-pre-line">
                {answer}
              </p>
            </div>
          </div>

      </div>
    </div>
  );
};

const FluidDynamics= () => {
  const content = [
    { 
      q: "Pressure and its SI unit", 
      a: "Pressure is defined as the force acting per unit area. The SI unit of pressure is Pascal (Pa), which is equivalent to one Newton per square meter (N/m²). Pressure is a scalar quantity and is measured in various units depending on the context, such as atmospheres (atm), bars, or millimeters of mercury (mmHg).Note the force needs to be perpendicular to the surface for it to be considered pressure." 
    },
     { 
      q: "Thrust" ,
      a: "Thrust is the force that propels an object forward in a fluid. It is generated by the reaction of the fluid being expelled from a propulsion system, such as in rockets or jet engines. The direction of thrust is opposite to the direction of the expelled fluid, as described by Newton's Third Law of Motion." 
    },
     { 
      q: "Pressure and its relations ", 
      a: "Pressure is related to force and area by the formula P = F/A, where P is pressure, F is the force applied, and A is the area over which the force is distributed. This means that for a given force, increasing the area will decrease the pressure, while decreasing the area will increase the pressure." 
    },
    { 
      q: "Derivation of Pressure in Liquid", 
      a: "Total pressure = atmospheric pressure + liquid pressure = P₀ + rho * g * h, where P₀ is atmospheric pressure, rho is the density of the liquid, g is the acceleration due to gravity, and h is the depth below the surface.\n the derivation of pressure in a liquid can be understood by considering a column of liquid with a certain height (h) and density (rho).\nThe weight of the liquid column exerts a force on the area at the bottom of the column, which can be calculated as F = m * g, where m is the mass of the liquid and g is the acceleration due to gravity. \nThe mass of the liquid can be expressed as m = rho * V, where V is the volume of the liquid. \nSince V = A * h (where A is the area), we can substitute this into the force equation to get F = rho * A * h * g. \nFinally, we can calculate pressure using P = F/A, which simplifies to P = rho * g * h." 
    },
    { 
      q: "Laws of liquid pressure",
      a: "The laws of liquid pressure are: \n1) Liquid pressure increases with depth. \n2) Liquid pressure is the same at all points at the same depth in a liquid. \n3) Liquid pressure depends on the density of the liquid. \n4) Liquid pressure is independent of the shape of the container." 
    },
    { 
      q: "Pascals Law", 
      a: "Pascal's Law states that when pressure is applied to a confined fluid, the pressure is transmitted equally in all directions throughout the fluid. This principle is fundamental in hydraulic systems, where a small force applied to a small area can be magnified to produce a larger force on a larger area, as long as the fluid is incompressible and confined within a closed system." 
    },
     { 
      q: "Hydraulic Machines", 
      a: "Hydraulic machines are devices that use the principles of Pascal's Law to transmit and multiply forces in fluids. They operate by applying a small force over a small area, which is then transmitted through an incompressible fluid to a larger area, resulting in a larger output force. Examples of hydraulic machines include hydraulic lifts, hydraulic brakes, and hydraulic presses. These machines are widely used in industries such as automotive, construction, and manufacturing due to their ability to generate large forces with relatively small input forces." 
    },
     { 
      q: "Barometers and their types", 
      a: "Barometers are instruments used to measure atmospheric pressure. There are two main types of barometers: \n1) Mercury Barometer - This type uses a column of mercury to measure pressure. The height of the mercury column changes with atmospheric pressure. \n2) Aneroid Barometer - This type uses a sealed metal box called an aneroid cell, which expands or contracts with changes in atmospheric pressure. The movement of the cell is translated into a reading on a dial." 
    },
    {
        q: "Manometers and their types",
        a: "Manometers are devices used to measure the pressure of gases or liquids. There are two main types of manometers: \n1) U-tube Manometer - This type consists of a U-shaped tube filled with a liquid (usually mercury or water). The difference in the height of the liquid columns indicates the pressure difference. \n2) Digital Manometer - This type uses electronic sensors to measure pressure and provides a digital readout. It is more accurate and easier to use than traditional manometers."
    },
    {
        q:"Upthrust and Buoyancy",
        a:"Upthrust, also known as buoyant force, is the upward force exerted by a fluid on an object that is partially or fully submerged in it. This force is equal to the weight of the fluid displaced by the object, as described by Archimedes' principle. The buoyant force allows objects to float or rise in a fluid, and its magnitude depends on the density of the fluid and the volume of fluid displaced."
    },
    {
        q:"Archimedes' Principle",
        a:"Archimedes' Principle states that any object, wholly or partially submerged in a fluid, experiences an upward buoyant force equal to the weight of the fluid that the object displaces. This principle explains why objects float or sink in fluids and is fundamental in understanding buoyancy and fluid mechanics.\nThe principle can be mathematically expressed as F_b = rho * V * g, where F_b is the buoyant force, rho is the density of the fluid, V is the volume of fluid displaced by the object, and g is the acceleration due to gravity."
    },
    {
        q:"Floatation and its conditions",
        a:"Floatation is the ability of an object to float in a fluid. For an object to float, the buoyant force acting on it must be equal to or greater than its weight. The conditions for floatation are: \n1) The density of the object must be less than the density of the fluid. \n2) The volume of fluid displaced by the object must be sufficient to generate a buoyant force equal to the object's weight. \n3) The object must be able to displace enough fluid to counteract its weight, which is determined by its shape and size."
    },
    {
        q: "Relative density and its applications",
        a: "Relative density, also known as specific gravity, is the ratio of the density of a substance to the density of a reference substance (usually water for liquids).\n It is a dimensionless quantity that indicates how many times denser a substance is compared to the reference substance. \nApplications of relative density include determining whether an object will float or sink in a fluid, identifying substances based on their density, and calculating the concentration of solutions in chemistry."
    }
  ];

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-6xl mx-auto">
        
        <header className="text-center mb-16">
          <h1 className="text-4xl font-extrabold text-gray-900 mb-4">
             <span className="text-blue-600">Fluid Dynamics</span>
          </h1>
          <p className="text-gray-600 italic">Click any card to flip it and reveal the answer.</p>
        </header>

        

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {content.map((item, index) => (
            <Flashcard key={index} question={item.q} answer={item.a} />
          ))}
        </div>

        <footer className="mt-20 text-center text-gray-400 text-sm">
          <p>© 2026 Amitesh Tutorials - Master Physics Chapter-wise</p>
        </footer>
      </div>
    </div>
  );
};

export default FluidDynamics;